# Generated by Django 4.2.7 on 2026-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="otp_type",
            field=models.CharField(
                choices=[
                    ("email", "Email Verification"),
                    ("phone", "Phone Verification"),
                    ("login", "Login OTP"),
                    ("signup", "Signup OTP"),
                    ("password", "Password Reset"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
