# Generated by Django 4.2.7 on 2026-05-24 17:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study_materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("video", "Video Lecture"),
                            ("ebook", "E-Book"),
                            ("current_affair", "Current Affair"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "objectives",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="What students will learn"
                    ),
                ),
                (
                    "requirements",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Prerequisites"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_thumbnails/"
                    ),
                ),
                (
                    "promo_video",
                    models.URLField(blank=True, help_text="YouTube or Vimeo URL"),
                ),
                ("is_free", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_lectures", models.IntegerField(default=0)),
                (
                    "total_duration",
                    models.IntegerField(
                        default=0, help_text="Total duration in minutes"
                    ),
                ),
                ("total_enrollments", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("icon", models.CharField(default="fa-book", max_length=50)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Course Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "lecture_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Lecture"),
                            ("document", "Document"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube or Vimeo URL"),
                ),
                ("video_embed_code", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="lecture_documents/"
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(blank=True)),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in minutes"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_free_preview", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("handwritten", "Handwritten Notes"),
                            ("typed", "Typed Notes"),
                            ("summary", "Chapter Summary"),
                            ("formula", "Formula Sheet"),
                        ],
                        default="typed",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="notes/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="note_covers/"),
                ),
                ("author", models.CharField(blank=True, max_length=100)),
                ("pages", models.IntegerField(default=0)),
                ("file_size", models.CharField(blank=True, max_length=50)),
                ("views", models.IntegerField(default=0)),
                ("downloads", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("is_free", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="exams.exam",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="exams.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="study_materials.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress",
                    models.FloatField(default=0, help_text="Completion percentage"),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="study_materials.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="UserLectureProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_watched", models.DateTimeField(auto_now=True)),
                (
                    "watch_time",
                    models.IntegerField(default=0, help_text="Watch time in seconds"),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="study_materials.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lecture")},
            },
        ),
        migrations.RemoveField(
            model_name="studymaterial",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="userbookmark",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userbookmark",
            name="material",
        ),
        migrations.RemoveField(
            model_name="userbookmark",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="currentaffair",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name_plural": "Current Affairs",
            },
        ),
        migrations.AlterModelOptions(
            name="ebook",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="videolecture",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="ebook",
            old_name="file",
            new_name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="ebook",
            name="category",
        ),
        migrations.RemoveField(
            model_name="videolecture",
            name="category",
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="category",
            field=models.CharField(
                choices=[
                    ("national", "National"),
                    ("international", "International"),
                    ("economy", "Economy"),
                    ("science", "Science & Technology"),
                    ("environment", "Environment"),
                    ("sports", "Sports"),
                    ("appointments", "Appointments"),
                    ("awards", "Awards & Honors"),
                    ("defence", "Defence"),
                    ("other", "Other"),
                ],
                default="national",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="current_affairs/"
            ),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="important_for",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="summary",
            field=models.TextField(blank=True, help_text="Short summary for listing"),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="currentaffair",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ebook",
            name="edition",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ebook",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ebooks",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="ebook",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ebook",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ebook",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ebook",
            name="pages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ebook",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ebook",
            name="publisher",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="ebook",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="ebook",
            name="tags",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="ebook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ebook",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ebook",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_lectures",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_lectures",
                to="exams.subject",
            ),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="tags",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="videolecture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="currentaffair",
            name="source",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="currentaffair",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="author",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="videolecture",
            name="duration",
            field=models.CharField(help_text="e.g., 15:30", max_length=50),
        ),
        migrations.AlterField(
            model_name="videolecture",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="video_thumbnails/"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="StudyMaterial",
        ),
        migrations.DeleteModel(
            name="UserBookmark",
        ),
        migrations.AddField(
            model_name="lecture",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="study_materials.section",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="study_materials.coursecategory",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="exams.exam",
            ),
        ),
    ]
