# Generated by Django 4.2.7 on 2026-05-24 07:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True, help_text="e.g., SBI PO, IBPS Clerk", max_length=50
                    ),
                ),
                (
                    "exam_level",
                    models.CharField(
                        choices=[
                            ("national", "National Level"),
                            ("state", "State Level"),
                            ("bank", "Bank Level"),
                            ("other", "Other"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                ("eligibility", ckeditor.fields.RichTextField(blank=True)),
                ("exam_pattern", ckeditor.fields.RichTextField(blank=True)),
                ("syllabus", ckeditor.fields.RichTextField(blank=True)),
                (
                    "important_dates",
                    models.TextField(
                        blank=True, help_text="JSON format for important dates"
                    ),
                ),
                ("official_website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="exam_logos/"),
                ),
                ("duration_minutes", models.IntegerField(default=180)),
                ("total_marks", models.IntegerField(default=600)),
                ("total_questions", models.IntegerField(default=100)),
                ("negative_marking", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExamCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-university",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Exam Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "weightage",
                    models.FloatField(
                        default=0, help_text="Percentage weightage in exam"
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("total_marks", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "weightage",
                    models.FloatField(
                        default=0, help_text="Percentage weightage in subject"
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="exams.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("notes", "Notes"),
                            ("video", "Video Lecture"),
                            ("pdf", "PDF Document"),
                            ("ebook", "E-Book"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="study_materials/"
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                (
                    "duration",
                    models.CharField(blank=True, help_text="For videos", max_length=50),
                ),
                ("downloads", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("is_free", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="exams.exam",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="exams.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice - Single Answer"),
                            ("multiple_correct", "Multiple Choice - Multiple Answers"),
                            ("numerical", "Numerical Value"),
                            ("true_false", "True/False"),
                            ("match", "Match the Following"),
                            ("passage", "Passage Based"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("question_text", ckeditor.fields.RichTextField()),
                (
                    "question_text_hindi",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("marks", models.FloatField(default=1)),
                ("negative_marks", models.FloatField(default=0)),
                (
                    "estimated_time",
                    models.IntegerField(default=60, help_text="Time in seconds"),
                ),
                ("explanation", ckeditor.fields.RichTextField(blank=True)),
                ("explanation_hindi", ckeditor.fields.RichTextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma separated tags", max_length=500
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.TextField()),
                ("option_text_hindi", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", ckeditor.fields.RichTextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                ("announcement_date", models.DateTimeField()),
                ("is_important", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["-announcement_date"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="exams.examcategory",
            ),
        ),
    ]
