# Generated by Django 4.2.7 on 2026-05-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveTestCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Mega Mock Test, Live Quiz, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        default="Live Now",
                        help_text="e.g., 🔥 Live Now, ⚡ Starting Soon",
                        max_length=50,
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="yellow",
                        help_text="yellow, red, green, blue, purple",
                        max_length=20,
                    ),
                ),
                ("total_participants", models.IntegerField(default=0)),
                (
                    "enrolled_percentage",
                    models.IntegerField(
                        default=0, help_text="Percentage of seats filled (0-100)"
                    ),
                ),
                ("has_timer", models.BooleanField(default=True)),
                ("timer_hours", models.IntegerField(default=0)),
                ("timer_minutes", models.IntegerField(default=15)),
                ("timer_seconds", models.IntegerField(default=30)),
                (
                    "button_text",
                    models.CharField(default="Join Live Test Now →", max_length=100),
                ),
                (
                    "button_url",
                    models.URLField(blank=True, help_text="URL when button is clicked"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured position"
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_cards",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
