# Generated by Django 4.2.7 on 2026-05-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0002_livetestcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("mock_test", "Mock Test"),
                            ("practice", "Practice Set"),
                            ("puzzle", "Puzzle"),
                        ],
                        default="quiz",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("total_questions", models.IntegerField(default=10)),
                ("duration_minutes", models.IntegerField(default=15)),
                ("xp_reward", models.IntegerField(default=500)),
                ("coin_reward", models.IntegerField(default=100)),
                (
                    "test_url",
                    models.URLField(blank=True, help_text="URL to the challenge test"),
                ),
                ("challenge_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("total_participants", models.IntegerField(default=0)),
                ("total_completed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mock_test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mocktests.mocktest",
                    ),
                ),
            ],
            options={
                "ordering": ["-challenge_date", "-is_featured"],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                            ("exam_wise", "Exam Wise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(default=0)),
                ("rank", models.IntegerField()),
                ("accuracy", models.FloatField(default=0)),
                ("total_tests", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="exams.dailychallenge",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["period", "-score"],
                        name="exams_leade_period_068cc8_idx",
                    ),
                    models.Index(
                        fields=["exam", "period"], name="exams_leade_exam_id_d586d9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChallengeParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0)),
                ("percentage", models.FloatField(default=0)),
                (
                    "time_taken",
                    models.IntegerField(default=0, help_text="Time in seconds"),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("xp_earned", models.IntegerField(default=0)),
                ("coins_earned", models.IntegerField(default=0)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="exams.dailychallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "time_taken"],
                "unique_together": {("challenge", "user")},
            },
        ),
    ]
