# Generated by Django 4.2.7 on 2026-05-25 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
        ("exams", "0003_dailychallenge_leaderboardentry_challengeparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="free_mock_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="mocktests.mocktest",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="free_mock_test_url",
            field=models.URLField(
                blank=True, help_text="Alternative URL for free mock test"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_free",
            field=models.BooleanField(default=True, help_text="Free exam access"),
        ),
        migrations.AddField(
            model_name="exam",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price for paid exams",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="payments.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="ExamEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("user", "exam")},
            },
        ),
    ]
