# Generated by Django 4.2.7 on 2026-05-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_exam_discounted_price_exam_free_mock_test_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="discounted_price",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="free_mock_test",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="free_mock_test_url",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="is_free",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="price",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="subscription_plan",
        ),
        migrations.DeleteModel(
            name="ExamEnrollment",
        ),
    ]
