# Generated by Django 4.2.7 on 2026-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_remove_exam_discounted_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_paid",
            field=models.BooleanField(
                default=False,
                help_text="If True, users need to pay to access this exam",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Price in INR", max_digits=10
            ),
        ),
    ]
