# Generated by Django 6.0.6 on 2026-06-28 08:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_exam_discount_price_exam_is_paid_exam_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, help_text="Explanation for the answer"
            ),
        ),
    ]
