# Generated by Django 4.2.7 on 2026-06-06 15:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_exam_discount_price_exam_is_paid_exam_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Explanation for the answer"
            ),
        ),
    ]
