# Generated by Django 4.2.7 on 2026-05-30 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_remove_exam_discounted_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyactivity",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="topicperformance",
            options={"ordering": ["-accuracy"]},
        ),
        migrations.RenameField(
            model_name="dailyactivity",
            old_name="questions_solved",
            new_name="correct_answers",
        ),
        migrations.RenameField(
            model_name="topicperformance",
            old_name="questions_attempted",
            new_name="total_questions",
        ),
        migrations.RenameField(
            model_name="userperformance",
            old_name="accuracy",
            new_name="overall_accuracy",
        ),
        migrations.RenameField(
            model_name="userperformance",
            old_name="best_score",
            new_name="percentile",
        ),
        migrations.RenameField(
            model_name="userperformance",
            old_name="correct_answers",
            new_name="rank",
        ),
        migrations.RenameField(
            model_name="userperformance",
            old_name="total_attempts",
            new_name="total_correct_answers",
        ),
        migrations.RenameField(
            model_name="userperformance",
            old_name="total_questions_answered",
            new_name="total_questions_attempted",
        ),
        migrations.RenameField(
            model_name="userperformance",
            old_name="wrong_answers",
            new_name="total_skipped_answers",
        ),
        migrations.AlterUniqueTogether(
            name="userperformance",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="topicperformance",
            name="strength_score",
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="questions_attempted",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="wrong_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topicperformance",
            name="is_strong",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topicperformance",
            name="is_weak",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topicperformance",
            name="wrong_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="total_tests_taken",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="total_time_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="total_wrong_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyactivity",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="dailyactivity",
            name="time_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="topicperformance",
            name="average_time",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="topicperformance",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_performances",
                to="exams.topic",
            ),
        ),
        migrations.AlterField(
            model_name="topicperformance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_performances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userperformance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="userperformance",
            name="exam",
        ),
        migrations.CreateModel(
            name="SubjectPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                ("wrong_answers", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                ("average_time", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_performances",
                        to="exams.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "subject")},
            },
        ),
        migrations.CreateModel(
            name="ExamPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_attempts", models.IntegerField(default=0)),
                ("total_correct", models.IntegerField(default=0)),
                ("total_wrong", models.IntegerField(default=0)),
                ("total_skipped", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                ("average_score", models.FloatField(default=0)),
                ("best_score", models.FloatField(default=0)),
                ("last_attempt_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_performances",
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "exam")},
            },
        ),
    ]
