# Generated by Django 4.2.7 on 2026-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_dailyactivity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userperformance",
            name="badges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="coins",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="last_activity_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="total_xp",
            field=models.IntegerField(default=0),
        ),
    ]
