# Generated by Django 4.2.7 on 2026-05-24 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Length Mock Test"),
                            ("sectional", "Sectional Test"),
                            ("topic", "Topic Wise Test"),
                            ("practice", "Practice Test"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                ("duration_minutes", models.IntegerField(default=60)),
                ("total_questions", models.IntegerField(default=100)),
                ("total_marks", models.IntegerField(default=200)),
                ("passing_marks", models.IntegerField(default=80)),
                ("negative_marking", models.BooleanField(default=True)),
                ("negative_mark_value", models.FloatField(default=0.25)),
                ("marks_per_question", models.FloatField(default=2)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("shuffle_options", models.BooleanField(default=True)),
                ("attempts_allowed", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_tests",
                        to="exams.exam",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(default=0)),
                ("percentage", models.FloatField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("percentile", models.FloatField(blank=True, null=True)),
                ("correct_answers", models.IntegerField(default=0)),
                ("wrong_answers", models.IntegerField(default=0)),
                ("skipped_answers", models.IntegerField(default=0)),
                ("total_time_taken", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mock_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mocktests.mocktest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("is_skipped", models.BooleanField(default=False)),
                ("marks_obtained", models.FloatField(default=0)),
                ("time_taken", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="mocktests.testattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.question"
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
        migrations.CreateModel(
            name="MockTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.FloatField(default=2)),
                ("order", models.IntegerField(default=0)),
                (
                    "mock_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mocktests.mocktest",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.question"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("mock_test", "question")},
            },
        ),
    ]
