# Generated by Django 4.2.7 on 2026-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0002_auto_20260526_1328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mocktest",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
    ]
