# Generated by Django 4.2.7 on 2026-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0003_alter_mocktest_is_free"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mocktest",
            name="is_free",
        ),
        migrations.AddField(
            model_name="mocktest",
            name="is_paid",
            field=models.BooleanField(
                default=False,
                help_text="If True, users need to pay to access this test",
            ),
        ),
        migrations.AlterField(
            model_name="mocktest",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Price in INR", max_digits=10
            ),
        ),
    ]
