# Generated by Django 4.2.7 on 2026-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0004_remove_mocktest_is_free_mocktest_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
