# Generated by Django 4.2.7 on 2026-06-14 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mocktests", "0005_testattempt_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
