# Generated by Django 4.2.7 on 2026-06-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0006_alter_testattempt_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="not_answered_count",
            field=models.IntegerField(default=0),
        ),
    ]
