# Generated by Django 4.2.7 on 2026-06-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0007_add_not_answered_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="is_marked_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
