# Generated by Django 4.2.7 on 2026-06-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktests", "0008_testattempt_is_marked_for_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testattempt",
            name="is_marked_for_review",
        ),
        migrations.AddField(
            model_name="testanswer",
            name="is_marked_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
