# Generated by Django 6.0.6 on 2026-06-29 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0009_remove_testattempt_is_marked_for_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'status', '-end_time'], name='mocktests_t_user_id_a5d63b_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['mock_test', 'status'], name='mocktests_t_mock_te_fba9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['session_id', 'mock_test', 'status'], name='mocktests_t_session_6b8cf3_idx'),
        ),
    ]
