# Generated by Django 4.2.7 on 2026-05-24 18:08

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Email"),
                            ("exam_reminder", "Exam Reminder"),
                            ("result_announcement", "Result Announcement"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("subscription_expiry", "Subscription Expiry"),
                            ("mock_test_reminder", "Mock Test Reminder"),
                            ("password_reset", "Password Reset"),
                            ("newsletter", "Newsletter"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="Use {{ user.first_name }}, {{ user.email }}, etc. for dynamic content"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_exam_reminders", models.BooleanField(default=True)),
                ("email_result_updates", models.BooleanField(default=True)),
                ("email_mock_test_alerts", models.BooleanField(default=True)),
                ("email_payment_updates", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=False)),
                ("email_promotions", models.BooleanField(default=False)),
                ("sms_exam_reminders", models.BooleanField(default=False)),
                ("sms_result_updates", models.BooleanField(default=False)),
                ("sms_mock_test_alerts", models.BooleanField(default=False)),
                ("sms_payment_updates", models.BooleanField(default=True)),
                ("in_app_notifications", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exam", "Exam Update"),
                            ("result", "Result Announcement"),
                            ("mock_test", "Mock Test"),
                            ("payment", "Payment"),
                            ("course", "Course Update"),
                            ("system", "System Notification"),
                            ("promotion", "Promotion"),
                            ("reminder", "Reminder"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_broadcast", models.BooleanField(default=False)),
                (
                    "action_url",
                    models.URLField(
                        blank=True, help_text="URL to redirect when clicked"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(blank=True, default="View Details", max_length=50),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="notificatio_is_read_1cb71a_idx",
                    ),
                    models.Index(
                        fields=["scheduled_time", "is_sent"],
                        name="notificatio_schedul_94fac2_idx",
                    ),
                ],
            },
        ),
    ]
