# Generated by Django 4.2.7 on 2026-05-24 18:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", ckeditor.fields.RichTextField()),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("banner", "Top Banner"),
                            ("card", "Card"),
                            ("marquee", "Marquee/Ticker"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="bg-blue-500",
                        help_text="Tailwind background color",
                        max_length=20,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="text-white",
                        help_text="Tailwind text color",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_urgent", models.BooleanField(default=False)),
                (
                    "is_sticky",
                    models.BooleanField(default=False, help_text="Always show at top"),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_sticky", "order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="template",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="user",
        ),
        migrations.RemoveField(
            model_name="smslog",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_05b4bc_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_is_read_1cb71a_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_schedul_94fac2_idx",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="read_at",
            new_name="end_date",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="category",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_broadcast",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_sent",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="scheduled_time",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sent_at",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="display_location",
            field=models.CharField(
                choices=[
                    ("navbar", "Navbar Bell Icon Only"),
                    ("homepage", "Homepage Section Only"),
                    ("both", "Both Navbar and Homepage"),
                    ("popup", "Popup Modal"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="notification_images/"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="show_as_popup",
            field=models.BooleanField(
                default=False, help_text="Show as popup modal on page load"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="show_bell_icon",
            field=models.BooleanField(
                default=True, help_text="Show bell icon in navbar"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="show_on_homepage",
            field=models.BooleanField(
                default=True, help_text="Show in homepage notifications section"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="notification",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="EmailLog",
        ),
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
        migrations.DeleteModel(
            name="NotificationPreference",
        ),
        migrations.DeleteModel(
            name="SMSLog",
        ),
        migrations.AddField(
            model_name="notificationview",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views_log",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationclick",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks_log",
                to="notifications.notification",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationview",
            unique_together={("notification", "session_key")},
        ),
    ]
