# Generated by Django 4.2.7 on 2026-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_announcement_notificationclick_notificationview_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="show_bell_icon",
            field=models.BooleanField(
                default=True, help_text="Show in navbar bell icon"
            ),
        ),
    ]
